/** ==================================================================================================================
Description	:	Contains the list of Database Groups for Redgate Multiscript, because Multiscript is weird about the 
				group GroupGuids and does not allow a group to be created if it has the same name but different group
				GroupGuid as an existing group

Fields	:
	EnvironmentCode	:	Code for the environment
 	DatabaseType	:	Code for the Database Type
	NodeType		:	Which servers do we want to connect to?
							CNAME 	= connect to the CNAME
							All		= connect to each server node
	AuthType		:	What type of authentication?
							Windows = use Windows Authentication
							SQL		= use SQL Authetication
	SQLUserName		:	If AuthType = SQL, what is the SQL Server User name?  If its anything but DeployUser, the code will use the empty string record
	GroupGuid		: 	Unique GroupGuid generated by MultiScript for that group
	GroupName		: 	Name of the Database Group
				
Notes
	To add a new Group to this list you need to generate a guid/GroupGuid that Multiscript likes (just using NEWID() does not work!)
		1. Open Multiscript
		2. Click "Configure" next to the Database Distribution List dropdown
		3. Click "New" 
		4. Put the desired group name
		5. Click "Create"
 		6. Click "OK"
 		7. Click the "Tools" menu option
		8. Click "Export Distribution Lists"
		9. Click "Deselect All" 
		10. Check the box(es) for the new group(s) you have created
		11. Click "Export"
		12. Select your save location and export file name
		13. Click "Save"
		14. Open the file in a text editor 
		15. For each group you created
			a. Add a new row in this view
			b. Copy the value for the "<guid>" attribute for the group
			c. Paste the value ^ into the GroupGuid column for that group's row
================================================================================================================== **/

CREATE VIEW dbo.View_RedgateMultiScriptDatabaseGroups

AS

	SELECT
		X.Env			AS EnvironmentCode
		, X.DBType		AS DatabaseType
		, X.NodeType
		, X.AuthType
		, X.SQLUserName
		, X.GroupGuid
		, X.GroupName
	FROM ( VALUES
		----------------------------------------------------------------------------------------------------------------------------------------
		-- DB1
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		  ( 'D'	, 'DB1'	, 'CNAME'	, 'Windows'	, NULL			, '65bf36c9-7841-480a-8790-062f7675f007', 'Dev - DB1 - WindowsAuth' )
		, ( 'T'	, 'DB1'	, 'CNAME'	, 'Windows'	, NULL			, '15f6002f-566b-407f-b8b1-574b66e7f19d', 'Test - DB1 - WindowsAuth' )
		, ( 'S'	, 'DB1'	, 'CNAME'	, 'Windows'	, NULL			, 'fa84332c-b577-4baa-8ab0-b3d7888dbf3a', 'Stage - DB1 - WindowsAuth' )
		, ( 'P'	, 'DB1'	, 'CNAME'	, 'Windows'	, NULL			, '93c63e5b-d4fa-4486-a3b3-04b8b1977de0', 'Prod - DB1 - WindowsAuth' )

		, ( 'D'	, 'DB1'	, 'All'		, 'Windows'	, NULL			, '0612e91c-2f7c-4951-bdd3-e4511dc9803d', 'Dev - DB1 - WindowsAuth - All Nodes' )
		, ( 'T'	, 'DB1'	, 'All'		, 'Windows'	, NULL			, '56b380f4-2f77-4cb1-95b3-e09f9a118fc0', 'Test - DB1 - WindowsAuth - All Nodes' )
		, ( 'S'	, 'DB1'	, 'All'		, 'Windows'	, NULL			, 'f9a4b659-e857-4856-9486-56247114c896', 'Stage - DB1 - WindowsAuth - All Nodes' )
		, ( 'P'	, 'DB1'	, 'All'		, 'Windows'	, NULL			, '384ccbaa-b98c-4324-9b3b-991e4d2e699f', 'Prod - DB1 - WindowsAuth - All Nodes' )

		, ( 'D'	, 'DB1'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '90dda479-be57-4720-807f-b844fe616159', 'Dev - DB1 - DeployUser' )
		, ( 'T'	, 'DB1'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'bcbf6401-1df4-4e38-89ba-ad5671ef1658', 'Test - DB1 - DeployUser' )
		, ( 'S'	, 'DB1'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'e975a402-7edb-4fec-ad0c-d42f65d3cc5f', 'Stage - DB1 - DeployUser' )
		, ( 'P'	, 'DB1'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'babf4758-5d1c-43a5-8109-a1aa1aa757f5', 'Prod - DB1 - DeployUser' )

		, ( 'D'	, 'DB1'	, 'All'		, 'SQL'		, 'DeployUser'	, '063bffd2-71e0-40e8-bd2f-f51893fd2886', 'Dev - DB1 - DeployUser - All Nodes' )
		, ( 'T'	, 'DB1'	, 'All'		, 'SQL'		, 'DeployUser'	, '9939f050-fa44-4389-b3de-d542a727af92', 'Test - DB1 - DeployUser - All Nodes' )
		, ( 'S'	, 'DB1'	, 'All'		, 'SQL'		, 'DeployUser'	, '1e017cbb-3cf3-407e-83ff-776abf7b1e21', 'Stage - DB1 - DeployUser - All Nodes' )
		, ( 'P'	, 'DB1'	, 'All'		, 'SQL'		, 'DeployUser'	, 'da012cf6-9de7-469c-9517-6d72112cea5e', 'Prod - DB1 - DeployUser - All Nodes' )

		, ( 'D'	, 'DB1'	, 'CNAME'	, 'SQL'		, ''			, '106fcaf7-a724-4903-b24b-cbfe40fdf7f9', 'Dev - DB1 - SQLAuth' )
		, ( 'T'	, 'DB1'	, 'CNAME'	, 'SQL'		, ''			, '387bae02-2122-452c-89af-567de607d231', 'Test - DB1 - SQLAuth' )
		, ( 'S'	, 'DB1'	, 'CNAME'	, 'SQL'		, ''			, '2e63a7bf-b05a-4681-b287-1edca7ce4940', 'Stage - DB1 - SQLAuth' )
		, ( 'P'	, 'DB1'	, 'CNAME'	, 'SQL'		, ''			, 'e6ad9301-de2e-4706-91c9-c5f2eb70bc34', 'Prod - DB1 - SQLAuth' )

		, ( 'D'	, 'DB1'	, 'All'		, 'SQL'		, ''			, '0704f198-e880-4f92-9001-27185c240f66', 'Dev - DB1 - SQLAuth - All Nodes' )
		, ( 'T'	, 'DB1'	, 'All'		, 'SQL'		, ''			, '13e87afb-ba88-46d4-a02b-34dcc6553d80', 'Test - DB1 - SQLAuth - All Nodes' )
		, ( 'S'	, 'DB1'	, 'All'		, 'SQL'		, ''			, 'ae4fdb3f-0c73-4801-9a1c-6d2230107c8b', 'Stage - DB1 - SQLAuth - All Nodes' )
		, ( 'P'	, 'DB1'	, 'All'		, 'SQL'		, ''			, '72fddeb9-aac5-464b-a08b-e6410eea0ec9', 'Prod - DB1 - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- DB2
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'DB2'	, 'CNAME'	, 'Windows'	, NULL			, '921784d8-c641-4d88-976d-f2ed88e10647', 'Dev - DB2 - WindowsAuth' )
		, ( 'T'	, 'DB2'	, 'CNAME'	, 'Windows'	, NULL			, '3f09caeb-abab-4388-8e58-f6970627b881', 'Test - DB2 - WindowsAuth' )
		, ( 'S'	, 'DB2'	, 'CNAME'	, 'Windows'	, NULL			, '882a4c0d-ec77-4edc-96d0-518027b5d21f', 'Stage - DB2 - WindowsAuth' )
		, ( 'P'	, 'DB2'	, 'CNAME'	, 'Windows'	, NULL			, '1f936338-da86-4002-9317-2d0856292ce2', 'Prod - DB2 - WindowsAuth' )

		, ( 'D'	, 'DB2'	, 'All'		, 'Windows'	, NULL			, '09d8ddd6-5227-4bd5-a2bd-34ff8c2c33bc', 'Dev - DB2 - WindowsAuth - All Nodes' )
		, ( 'T'	, 'DB2'	, 'All'		, 'Windows'	, NULL			, '7dacfb14-e8c5-438c-8350-1c2efeead6cb', 'Test - DB2 - WindowsAuth - All Nodes' )
		, ( 'S'	, 'DB2'	, 'All'		, 'Windows'	, NULL			, 'aa9d89b8-afa6-4c5a-be91-2b2e3e6bb535', 'Stage - DB2 - WindowsAuth - All Nodes' )
		, ( 'P'	, 'DB2'	, 'All'		, 'Windows'	, NULL			, 'cbfee66e-8aa7-496b-a960-ed3aad255ecf', 'Prod - DB2 - WindowsAuth - All Nodes' )

		, ( 'D'	, 'DB2'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'a3583223-edf5-4370-a22e-279db3ecca15', 'Dev - DB2 - DeployUser' )
		, ( 'T'	, 'DB2'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '51048143-f240-4c7f-b816-2e3eb33261b7', 'Test - DB2 - DeployUser' )
		, ( 'S'	, 'DB2'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '84ba00a4-ff77-4d28-9641-3f83f296fd0a', 'Stage - DB2 - DeployUser' )
		, ( 'P'	, 'DB2'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'cfacdbcf-5dc3-424e-84b8-bbca69f952ac', 'Prod - DB2 - DeployUser' )

		, ( 'D'	, 'DB2'	, 'CNAME'	, 'SQL'		, ''			, '6d9973ab-5a82-420e-a2c7-0d85fe412380', 'Dev - DB2 - SQLAuth' )
		, ( 'T'	, 'DB2'	, 'CNAME'	, 'SQL'		, ''			, '23aaa66e-43b6-4fe2-971c-30546a41d663', 'Test - DB2 - SQLAuth' )
		, ( 'S'	, 'DB2'	, 'CNAME'	, 'SQL'		, ''			, '4290dd09-8de7-44e9-bdbd-b47d532b2bcd', 'Stage - DB2 - SQLAuth' )
		, ( 'P'	, 'DB2'	, 'CNAME'	, 'SQL'		, ''			, 'b6062b0a-4cb2-407d-b040-8fc88416077c', 'Prod - DB2 - SQLAuth' )

		, ( 'D'	, 'DB2'	, 'All'		, 'SQL'		, 'DeployUser'	, '0af77160-a4c5-4966-a11a-2d75923ced7c', 'Dev - DB2 - DeployUser - All Nodes' )
		, ( 'T'	, 'DB2'	, 'All'		, 'SQL'		, 'DeployUser'	, '6deac2e5-a336-46d0-a958-255ddd126e5b', 'Test - DB2 - DeployUser - All Nodes' )
		, ( 'S'	, 'DB2'	, 'All'		, 'SQL'		, 'DeployUser'	, '7c6cae00-3294-4b27-9f7c-f7475a6ed7ac', 'Stage - DB2 - DeployUser - All Nodes' )
		, ( 'P'	, 'DB2'	, 'All'		, 'SQL'		, 'DeployUser'	, 'eb9baa58-8068-451c-8007-a7ad405b1d3c', 'Prod - DB2 - DeployUser - All Nodes' )

		, ( 'D'	, 'DB2'	, 'All'		, 'SQL'		, ''			, '0b73ed6c-9148-4a95-99f2-83dd8520fe44', 'Dev - DB2 - SQLAuth - All Nodes' )
		, ( 'T'	, 'DB2'	, 'All'		, 'SQL'		, ''			, 'f95d2872-583a-40ba-826b-3793098086af', 'Test - DB2 - SQLAuth - All Nodes' )
		, ( 'S'	, 'DB2'	, 'All'		, 'SQL'		, ''			, '37abe588-d792-4827-89a1-9dd5f122a99b', 'Stage - DB2 - SQLAuth - All Nodes' )
		, ( 'P'	, 'DB2'	, 'All'		, 'SQL'		, ''			, '69a359f3-5d0d-4321-b79b-32399ccb32ca', 'Prod - DB2 - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- DB3
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType	,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'DB3'		, 'CNAME'	, 'Windows'	, NULL			, '4eb32f6b-4424-4a82-ba59-fffabca5b3cf', 'Dev - DB3 - WindowsAuth' )
		, ( 'T'	, 'DB3'		, 'CNAME'	, 'Windows'	, NULL			, '22207793-9b08-4683-8da2-203768d46a2d', 'Test - DB3 - WindowsAuth' )
		, ( 'S'	, 'DB3'		, 'CNAME'	, 'Windows'	, NULL			, 'bf9d1284-8bb5-4089-963f-cf85977ac41e', 'Stage - DB3 - WindowsAuth' )
		, ( 'P'	, 'DB3'		, 'CNAME'	, 'Windows'	, NULL			, 'bb44c8db-f0df-4757-ac8e-fde2018679ca', 'Prod - DB3 - WindowsAuth' )

		, ( 'D'	, 'DB3'		, 'All'		, 'Windows'	, NULL			, '0c9fff24-cdb7-405c-a08d-039b6611d9ca', 'Dev - DB3 - WindowsAuth - All Nodes' )
		, ( 'T'	, 'DB3'		, 'All'		, 'Windows'	, NULL			, '4d29f138-d416-459c-be78-eb76ed04889d', 'Test - DB3 - WindowsAuth - All Nodes' )
		, ( 'S'	, 'DB3'		, 'All'		, 'Windows'	, NULL			, 'ce0ed0f4-ab15-4bb4-a75e-156a9f218693', 'Stage - DB3 - WindowsAuth - All Nodes' )
		, ( 'P'	, 'DB3'		, 'All'		, 'Windows'	, NULL			, 'a7889cb2-c7c0-418a-bb9b-e3796768ed2d', 'Prod - DB3 - WindowsAuth - All Nodes' )

		, ( 'D'	, 'DB3'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'd472690d-69f6-494f-b1df-f39e761d1bcc', 'Dev - DB3 - DeployUser' )
		, ( 'T'	, 'DB3'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '3ddac83e-77da-420f-9ec3-663d7baaed1f', 'Test - DB3 - DeployUser' )
		, ( 'S'	, 'DB3'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '676c403c-056f-4c58-a6a9-8a84d2c84ca7', 'Stage - DB3 - DeployUser' )
		, ( 'P'	, 'DB3'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'b0309f2b-0c56-4104-9e63-b07bbccc5ba9', 'Prod - DB3 - DeployUser' )

		, ( 'D'	, 'DB3'		, 'CNAME'	, 'SQL'		, ''			, '01f9327a-5237-409a-b94e-89c90b5df0a4', 'Dev - DB3 - SQLAuth' )
		, ( 'T'	, 'DB3'		, 'CNAME'	, 'SQL'		, ''			, '301e8388-7ca3-4363-9c0d-81a36864fea4', 'Test - DB3 - SQLAuth' )
		, ( 'S'	, 'DB3'		, 'CNAME'	, 'SQL'		, ''			, '69e001d7-feee-4e29-b347-8d08ff6fce1a', 'Stage - DB3 - SQLAuth' )
		, ( 'P'	, 'DB3'		, 'CNAME'	, 'SQL'		, ''			, 'e514bef2-d26c-4312-a1b0-304e887e9b82', 'Prod - DB3 - SQLAuth' )

		, ( 'D'	, 'DB3'		, 'All'		, 'SQL'		, 'DeployUser'	, '1257ac69-20c1-4ea0-b6bd-cfbe81cf3e5b', 'Dev - DB3 - DeployUser - All Nodes' )
		, ( 'T'	, 'DB3'		, 'All'		, 'SQL'		, 'DeployUser'	, '7305136e-e470-4955-b980-8e529f04a3b5', 'Test - DB3 - DeployUser - All Nodes' )
		, ( 'S'	, 'DB3'		, 'All'		, 'SQL'		, 'DeployUser'	, 'aa262244-615a-4a48-9522-9d3a073acfa7', 'Stage - DB3 - DeployUser - All Nodes' )
		, ( 'P'	, 'DB3'		, 'All'		, 'SQL'		, 'DeployUser'	, '81dd6aa8-768c-4d32-af02-299a01e82659', 'Prod - DB3 - DeployUser - All Nodes' )

		, ( 'D'	, 'DB3'		, 'All'		, 'SQL'		, ''			, '16f48db1-52eb-45f2-afff-975d2b756cff', 'Dev - DB3 - SQLAuth - All Nodes' )
		, ( 'T'	, 'DB3'		, 'All'		, 'SQL'		, ''			, '8731ca2f-fcaf-4604-9efd-1f13cff0625d', 'Test - DB3 - SQLAuth - All Nodes' )
		, ( 'S'	, 'DB3'		, 'All'		, 'SQL'		, ''			, '4652c0df-93b7-4f8c-9481-a89735299cf5', 'Stage - DB3 - SQLAuth - All Nodes' )
		, ( 'P'	, 'DB3'		, 'All'		, 'SQL'		, ''			, 'e6ce7521-00f2-46f9-9133-77a74c122e6c', 'Prod - DB3 - SQLAuth - All Nodes' )

	) AS X (Env	, DBType	,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName);
GO