/** ==================================================================================================================
Description	:	Contains the list of Database Groups for Redgate Multiscript, because Multiscript is weird about the 
				group GroupGuids and does not allow a group to be created if it has the same name but different group
				GroupGuid as an existing group

Fields	:
	EnvironmentCode	:	Code for the environment
							D = Dev
							T = Test
							S = Stage
							P = Prod
	DatabaseType	:	Code for the Database Type
	NodeType		:	Which servers do we want to connect to?
							CNAME 	= connect to the CNAME
							All		= connect to each server node
	AuthType		:	What type of authentication?
							Windows = use Windows Authentication
							SQL		= use SQL Authetication
	SQLUserName		:	If AuthType = SQL, what is the SQL Server User name?  If its anything but DeployUser, the code will use the empty string record
	GroupGuid		: 	Unique GroupGuid generated by MultiScript for that group
	GroupName		: 	Name of the Database Group
				
Notes
	To add a new Group to this list you need to generate a guid/GroupGuid that Multiscript likes (just using NEWID() does not work!)
		1. Open Multiscript
		2. Click "Configure" next to the Database Distribution List dropdown
		3. Click "New" 
		4. Put the desired group name
		5. Click "Create"
 		6. Click "OK"
 		7. Click the "Tools" menu option
		8. Click "Export Distribution Lists"
		9. Click "Deselect All" 
		10. Check the box(es) for the new group(s) you have created
		11. Click "Export"
		12. Select your save location and export file name
		13. Click "Save"
		14. Open the file in a text editor 
		15. For each group you created
			a. Add a new row in this view
			b. Copy the value for the "<guid>" attribute for the group
			c. Paste the value ^ into the GroupGuid column for that group's row
================================================================================================================== **/

CREATE VIEW dbo.View_RedgateMultiScriptDatabaseGroups

AS

	SELECT
		X.Env			AS EnvironmentCode
		, X.DBType		AS DatabaseType
		, X.NodeType
		, X.AuthType
		, X.SQLUserName
		, X.GroupGuid
		, X.GroupName
	FROM ( VALUES

		----------------------------------------------------------------------------------------------------------------------------------------
		-- DBA
		----------------------------------------------------------------------------------------------------------------------------------------
		-- DBA lists should always have ALL NODES of each server
		-- Env	, DBType	,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		  ( 'D'	, 'DBA'		, 'All'		, 'Windows'	, NULL			, 'd8865538-1975-489d-a3e0-e6fadb7d8030', 'Dev - DBA - WindowsAuth - All Nodes' )
		, ( 'T'	, 'DBA'		, 'All'		, 'Windows'	, NULL			, 'dd31906e-d6c8-4980-ac1e-b8a9b0a141e1', 'Test - DBA - WindowsAuth - All Nodes' )
		, ( 'S'	, 'DBA'		, 'All'		, 'Windows'	, NULL			, '3b417344-738c-45da-935e-26da3213cc27', 'Stage - DBA - WindowsAuth - All Nodes' )
		, ( 'P'	, 'DBA'		, 'All'		, 'Windows'	, NULL			, '696a136b-86fd-44f3-9ba6-813fc040ec30', 'Prod - DBA - WindowsAuth - All Nodes' )

		, ( 'D'	, 'DBA'		, 'All'		, 'SQL'		, 'DeployUser'	, 'f782de9a-bd13-44ad-8913-5aa8d820ee45', 'Dev - DBA - DeployUser - All Nodes' )
		, ( 'T'	, 'DBA'		, 'All'		, 'SQL'		, 'DeployUser'	, '7f598515-dc43-4519-ac1b-8479f2f91560', 'Test - DBA - DeployUser - All Nodes' )
		, ( 'S'	, 'DBA'		, 'All'		, 'SQL'		, 'DeployUser'	, 'daf41756-fee4-4793-a484-55f9d4880e04', 'Stage - DBA - DeployUser - All Nodes' )
		, ( 'P'	, 'DBA'		, 'All'		, 'SQL'		, 'DeployUser'	, '2af96afe-33dd-41df-8f23-3b298965b7a8', 'Prod - DBA - DeployUser - All Nodes' )

		, ( 'D'	, 'DBA'		, 'All'		, 'SQL'		, ''			, '9a2186b6-36ed-4973-b104-22d4c6cce904', 'Dev - DBA - SQLAuth - All Nodes' )
		, ( 'T'	, 'DBA'		, 'All'		, 'SQL'		, ''			, 'e96aea53-6d0a-4919-89f0-5ee18a6f3d05', 'Test - DBA - SQLAuth - All Nodes' )
		, ( 'S'	, 'DBA'		, 'All'		, 'SQL'		, ''			, '706d7dbd-ff13-4a82-b440-b59efeb624d8', 'Stage - DBA - SQLAuth - All Nodes' )
		, ( 'P'	, 'DBA'		, 'All'		, 'SQL'		, ''			, '4ed895f1-3474-4993-9f2a-08206a344636', 'Prod - DBA - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- A
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType	,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'A'		, 'CNAME'	, 'Windows'	, NULL			, 'd6f91e84-2931-4995-a99b-9e36a49b21a6', 'Dev - A - WindowsAuth' )
		, ( 'T'	, 'A'		, 'CNAME'	, 'Windows'	, NULL			, '460804db-b149-4500-9efb-50154b74e0fe', 'Test - A - WindowsAuth' )
		, ( 'S'	, 'A'		, 'CNAME'	, 'Windows'	, NULL			, '4fdaf6d7-2549-4000-a0b2-6b7283c64c94', 'Stage - A - WindowsAuth' )
		, ( 'P'	, 'A'		, 'CNAME'	, 'Windows'	, NULL			, 'a254cc66-0d2e-4d46-835a-6ef41f747d91', 'Prod - A - WindowsAuth' )

		, ( 'T'	, 'A'		, 'All'		, 'Windows'	, NULL			, '44c660e2-f069-4bec-b570-675b6a19864e', 'Test - A - WindowsAuth - All Nodes' )
		, ( 'S'	, 'A'		, 'All'		, 'Windows'	, NULL			, 'edba3971-2cfc-40bf-b7c7-7b4744f9cf18', 'Stage - A - WindowsAuth - All Nodes' )
		, ( 'P'	, 'A'		, 'All'		, 'Windows'	, NULL			, 'd858538a-ff83-4edf-9bf7-c20f009fa7bc', 'Prod - A - WindowsAuth - All Nodes' )

		, ( 'D'	, 'A'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '1dbf66ce-f332-439f-a2b2-ab18d266455f', 'Dev - A - DeployUser' )
		, ( 'T'	, 'A'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '1257ac69-20c1-4ea0-b6bd-cfbe81cf3e5b', 'Test - A - DeployUser' )
		, ( 'S'	, 'A'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '5b521051-be9c-45ac-809b-fc52a8ef510a', 'Stage - A - DeployUser' )
		, ( 'P'	, 'A'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '1a7c7cd8-574c-4057-b32e-71b16aff23ec', 'Prod - A - DeployUser' )

		, ( 'D'	, 'A'		, 'CNAME'	, 'SQL'		, ''			, 'ad6b3f42-43a5-4efa-8d82-e8cdb7ae0c02', 'Dev - A - SQLAuth' )
		, ( 'T'	, 'A'		, 'CNAME'	, 'SQL'		, ''			, '5dcac239-623e-4cad-8ca0-d3dbc83ffa39', 'Test - A - SQLAuth' )
		, ( 'S'	, 'A'		, 'CNAME'	, 'SQL'		, ''			, 'ecee3625-c8c2-4395-ae91-d822e76919cd', 'Stage - A - SQLAuth' )
		, ( 'P'	, 'A'		, 'CNAME'	, 'SQL'		, ''			, '6bbd9ad1-24f2-4a3c-8688-0c176a6a29f3', 'Prod - A - SQLAuth' )

		, ( 'T'	, 'A'		, 'All'		, 'SQL'		, 'DeployUser'	, '3394bc0e-fd22-4ee3-892f-6af2a7aa1951', 'Test - A - DeployUser - All Nodes' )
		, ( 'S'	, 'A'		, 'All'		, 'SQL'		, 'DeployUser'	, '09d8ddd6-5227-4bd5-a2bd-34ff8c2c33bc', 'Stage - A - DeployUser - All Nodes' )
		, ( 'P'	, 'A'		, 'All'		, 'SQL'		, 'DeployUser'	, '94b7e547-c198-4dde-ae68-24dacbda4ea0', 'Prod - A - DeployUser - All Nodes' )

		, ( 'T'	, 'A'		, 'All'		, 'SQL'		, ''			, '6103d0b5-0f4a-45cc-86a7-a8635d1b6f0b', 'Test - A - SQLAuth - All Nodes' )
		, ( 'S'	, 'A'		, 'All'		, 'SQL'		, ''			, '5230f214-bfc5-4ea0-90ce-a2e0ff3da9be', 'Stage - A - SQLAuth - All Nodes' )
		, ( 'P'	, 'A'		, 'All'		, 'SQL'		, ''			, '4791c47e-fa9d-4dbf-afb1-5e4304574bb4', 'Prod - A - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- AL
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'AL'	, 'CNAME'	, 'Windows'	, NULL			, '65bf36c9-7841-480a-8790-062f7675f007', 'Dev - AL - WindowsAuth' )
		, ( 'T'	, 'AL'	, 'CNAME'	, 'Windows'	, NULL			, '15f6002f-566b-407f-b8b1-574b66e7f19d', 'Test - AL - WindowsAuth' )
		, ( 'S'	, 'AL'	, 'CNAME'	, 'Windows'	, NULL			, 'fa84332c-b577-4baa-8ab0-b3d7888dbf3a', 'Stage - AL - WindowsAuth' )
		, ( 'P'	, 'AL'	, 'CNAME'	, 'Windows'	, NULL			, '93c63e5b-d4fa-4486-a3b3-04b8b1977de0', 'Prod - AL - WindowsAuth' )

		, ( 'T'	, 'AL'	, 'All'		, 'Windows'	, NULL			, '56b380f4-2f77-4cb1-95b3-e09f9a118fc0', 'Test - AL - WindowsAuth - All Nodes' )
		, ( 'S'	, 'AL'	, 'All'		, 'Windows'	, NULL			, 'f9a4b659-e857-4856-9486-56247114c896', 'Stage - AL - WindowsAuth - All Nodes' )
		, ( 'P'	, 'AL'	, 'All'		, 'Windows'	, NULL			, '384ccbaa-b98c-4324-9b3b-991e4d2e699f', 'Prod - AL - WindowsAuth - All Nodes' )

		, ( 'D'	, 'AL'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '90dda479-be57-4720-807f-b844fe616159', 'Dev - AL - DeployUser' )
		, ( 'T'	, 'AL'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'bcbf6401-1df4-4e38-89ba-ad5671ef1658', 'Test - AL - DeployUser' )
		, ( 'S'	, 'AL'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'e975a402-7edb-4fec-ad0c-d42f65d3cc5f', 'Stage - AL - DeployUser' )
		, ( 'P'	, 'AL'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'babf4758-5d1c-43a5-8109-a1aa1aa757f5', 'Prod - AL - DeployUser' )

		, ( 'T'	, 'AL'	, 'All'		, 'SQL'		, 'DeployUser'	, '9939f050-fa44-4389-b3de-d542a727af92', 'Test - AL - DeployUser - All Nodes' )
		, ( 'S'	, 'AL'	, 'All'		, 'SQL'		, 'DeployUser'	, '1e017cbb-3cf3-407e-83ff-776abf7b1e21', 'Stage - AL - DeployUser - All Nodes' )
		, ( 'P'	, 'AL'	, 'All'		, 'SQL'		, 'DeployUser'	, 'da012cf6-9de7-469c-9517-6d72112cea5e', 'Prod - AL - DeployUser - All Nodes' )

		, ( 'D'	, 'AL'	, 'CNAME'	, 'SQL'		, ''			, '106fcaf7-a724-4903-b24b-cbfe40fdf7f9', 'Dev - AL - SQLAuth' )
		, ( 'T'	, 'AL'	, 'CNAME'	, 'SQL'		, ''			, '387bae02-2122-452c-89af-567de607d231', 'Test - AL - SQLAuth' )
		, ( 'S'	, 'AL'	, 'CNAME'	, 'SQL'		, ''			, '2e63a7bf-b05a-4681-b287-1edca7ce4940', 'Stage - AL - SQLAuth' )
		, ( 'P'	, 'AL'	, 'CNAME'	, 'SQL'		, ''			, 'e6ad9301-de2e-4706-91c9-c5f2eb70bc34', 'Prod - AL - SQLAuth' )

		, ( 'T'	, 'AL'	, 'All'		, 'SQL'		, ''			, '13e87afb-ba88-46d4-a02b-34dcc6553d80', 'Test - AL - SQLAuth - All Nodes' )
		, ( 'S'	, 'AL'	, 'All'		, 'SQL'		, ''			, 'ae4fdb3f-0c73-4801-9a1c-6d2230107c8b', 'Stage - AL - SQLAuth - All Nodes' )
		, ( 'P'	, 'AL'	, 'All'		, 'SQL'		, ''			, '72fddeb9-aac5-464b-a08b-e6410eea0ec9', 'Prod - AL - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- B
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType		,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'B'			, 'CNAME'	, 'Windows'	, NULL			, 'fc4b82e2-4d50-493f-84e4-1be253ea6e75', 'Dev - B - WindowsAuth' )
		, ( 'T'	, 'B'			, 'CNAME'	, 'Windows'	, NULL			, '4609b496-1391-4721-af20-4f88846eb28a', 'Test - B - WindowsAuth' )
		, ( 'S'	, 'B'			, 'CNAME'	, 'Windows'	, NULL			, '4a9bdfa4-e59e-4e20-a656-08f4f3223fa4', 'Stage - B - WindowsAuth' )
		, ( 'P'	, 'B'			, 'CNAME'	, 'Windows'	, NULL			, 'bd047153-37f5-45ee-a8c7-cd97ed4c9373', 'Prod - B - WindowsAuth' )

		, ( 'T'	, 'B'			, 'All'		, 'Windows'	, NULL			, '332f34e0-1655-4e83-9004-4fe6ef454574', 'Test - B - WindowsAuth - All Nodes' )
		, ( 'S'	, 'B'			, 'All'		, 'Windows'	, NULL			, '5d56f68c-d352-4c16-98d7-f4c8730962b4', 'Stage - B - WindowsAuth - All Nodes' )
		, ( 'P'	, 'B'			, 'All'		, 'Windows'	, NULL			, '1912d683-09f8-4a59-8afe-548d15c9c4a4', 'Prod - B - WindowsAuth - All Nodes' )

		, ( 'D'	, 'B'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, '8f723e4a-96b0-4cf4-b6d8-ba78cd3b0669', 'Dev - B - DeployUser' )
		, ( 'T'	, 'B'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'b7726040-e62b-4494-bf44-d484ad178ab2', 'Test - B - DeployUser' )
		, ( 'S'	, 'B'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'cba027c7-6da6-467f-a370-1c7954395e69', 'Stage - B - DeployUser' )
		, ( 'P'	, 'B'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'cb58310d-dec1-4557-9b9e-fd7e059b4f59', 'Prod - B - DeployUser' )

		, ( 'T'	, 'B'			, 'All'		, 'SQL'		, 'DeployUser'	, 'ea302b72-e650-468d-8e08-a959f0a88704', 'Test - B - DeployUser - All Nodes' )
		, ( 'S'	, 'B'			, 'All'		, 'SQL'		, 'DeployUser'	, '200d9516-9aa9-4caf-bdca-e2bcaffc8ec1', 'Stage - B - DeployUser - All Nodes' )
		, ( 'P'	, 'B'			, 'All'		, 'SQL'		, 'DeployUser'	, '799bccc7-8af0-490b-8be5-dbd70ebbe1b0', 'Prod - B - DeployUser - All Nodes' )

		, ( 'D'	, 'B'			, 'CNAME'	, 'SQL'		, ''			, '0af77160-a4c5-4966-a11a-2d75923ced7c', 'Dev - B - SQLAuth' )
		, ( 'T'	, 'B'			, 'CNAME'	, 'SQL'		, ''			, '8a0e1bb7-06da-4197-a48e-994ef5c7cf24', 'Test - B - SQLAuth' )
		, ( 'S'	, 'B'			, 'CNAME'	, 'SQL'		, ''			, '6f7528bf-21a1-4f75-98c7-9e26de2f1811', 'Stage - B - SQLAuth' )
		, ( 'P'	, 'B'			, 'CNAME'	, 'SQL'		, ''			, '19a6f2fa-9cf5-403a-b5e9-24f5a671d5ab', 'Prod - B - SQLAuth' )

		, ( 'T'	, 'B'			, 'All'		, 'SQL'		, ''			, 'b0d20eb7-36f1-43f9-8c5f-2511ddc01fdc', 'Test - B - SQLAuth - All Nodes' )
		, ( 'S'	, 'B'			, 'All'		, 'SQL'		, ''			, 'a5fac828-ebe7-4500-b55a-4f8a1c6e3447', 'Stage - B - SQLAuth - All Nodes' )
		, ( 'P'	, 'B'			, 'All'		, 'SQL'		, ''			, '4526471a-da41-4164-a32f-700671126c71', 'Prod - B - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- C
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'C'	, 'CNAME'	, 'Windows'	, NULL			, '0b73ed6c-9148-4a95-99f2-83dd8520fe44', 'Dev - C - WindowsAuth' )
		, ( 'T'	, 'C'	, 'CNAME'	, 'Windows'	, NULL			, '3a14028b-b273-4fab-b339-9373a3f73bc3', 'Test - C - WindowsAuth' )
		, ( 'S'	, 'C'	, 'CNAME'	, 'Windows'	, NULL			, 'f8c68694-a040-4a3e-8ee4-3cb2e6591c14', 'Stage - C - WindowsAuth' )
		, ( 'P'	, 'C'	, 'CNAME'	, 'Windows'	, NULL			, 'c90e89b4-b875-48d7-8f97-b43ee52146fb', 'Prod - C - WindowsAuth' )

		, ( 'T'	, 'C'	, 'All'		, 'Windows'	, NULL			, '6d8b7d0c-1d07-4654-8778-fb7c9cd08b98', 'Test - C - WindowsAuth - All Nodes' )
		, ( 'S'	, 'C'	, 'All'		, 'Windows'	, NULL			, 'af074dc3-8cd0-4d7a-8742-0976f9c46714', 'Stage - C - WindowsAuth - All Nodes' )
		, ( 'P'	, 'C'	, 'All'		, 'Windows'	, NULL			, '916492db-3710-4eb9-bbeb-e7f274a543b5', 'Prod - C - WindowsAuth - All Nodes' )

		, ( 'D'	, 'C'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'a28c4ec8-1180-4b95-9eff-b89e99f3891e', 'Dev - C - DeployUser' )
		, ( 'T'	, 'C'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '3f0ebe96-1514-4534-aafa-bce1c7eed99f', 'Test - C - DeployUser' )
		, ( 'S'	, 'C'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'fd27144c-17ed-4bcf-b43a-bf982365cef3', 'Stage - C - DeployUser' )
		, ( 'P'	, 'C'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '53dcf0c7-4952-4232-b0e3-2669b4b8d2ea', 'Prod - C - DeployUser' )

		, ( 'D'	, 'C'	, 'CNAME'	, 'SQL'		, ''			, 'e858d130-b719-459d-b3fc-7f07a97f9f35', 'Dev - C - SQLAuth' )
		, ( 'T'	, 'C'	, 'CNAME'	, 'SQL'		, ''			, '1a32d704-51ee-4391-9169-07694649060e', 'Test - C - SQLAuth' )
		, ( 'S'	, 'C'	, 'CNAME'	, 'SQL'		, ''			, '35578f6f-f80b-402f-b9a9-c47a7eaa1a92', 'Stage - C - SQLAuth' )
		, ( 'P'	, 'C'	, 'CNAME'	, 'SQL'		, ''			, '3ba4f9b3-9094-4d91-b2c3-e7a1e20fad40', 'Prod - C - SQLAuth' )

		, ( 'T'	, 'C'	, 'All'		, 'SQL'		, 'DeployUser'	, '5799766b-ce99-4e48-b0d0-0b1641a7a046', 'Test - C - DeployUser - All Nodes' )
		, ( 'S'	, 'C'	, 'All'		, 'SQL'		, 'DeployUser'	, 'c5148387-2773-4cd1-bbf8-88c8c6cc757e', 'Stage - C - DeployUser - All Nodes' )
		, ( 'P'	, 'C'	, 'All'		, 'SQL'		, 'DeployUser'	, '9bd1e10b-300c-487e-aa1c-ecf29d6ae186', 'Prod - C - DeployUser - All Nodes' )

		, ( 'T'	, 'C'	, 'All'		, 'SQL'		, ''			, '6a23bf18-7664-4ea4-ad9d-6377dbabccbe', 'Test - C - SQLAuth - All Nodes' )
		, ( 'S'	, 'C'	, 'All'		, 'SQL'		, ''			, '3343e9bc-5d7e-4a87-846a-f9110afe4b17', 'Stage - C - SQLAuth - All Nodes' )
		, ( 'P'	, 'C'	, 'All'		, 'SQL'		, ''			, '1e1386bd-d735-41eb-8ff4-db5e1cea87b7', 'Prod - C - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- E
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType		,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'E'			, 'CNAME'	, 'Windows'	, NULL			, '0612e91c-2f7c-4951-bdd3-e4511dc9803d', 'Dev - E - WindowsAuth' )
		, ( 'T'	, 'E'			, 'CNAME'	, 'Windows'	, NULL			, 'dd8c4e6b-72a7-45c6-bc17-0a05304b6dc5', 'Test - E - WindowsAuth' )
		, ( 'S'	, 'E'			, 'CNAME'	, 'Windows'	, NULL			, '8ca0014e-948d-49bc-92ce-4a516ae12338', 'Stage - E - WindowsAuth' )
		, ( 'P'	, 'E'			, 'CNAME'	, 'Windows'	, NULL			, '3db7fcc9-8cea-466d-b58a-13f30f6b9760', 'Prod - E - WindowsAuth' )

		, ( 'T'	, 'E'			, 'All'		, 'Windows'	, NULL			, '5bface6b-bb22-48f5-a23b-48ce141b7e81', 'Test - E - WindowsAuth - All Nodes' )
		, ( 'S'	, 'E'			, 'All'		, 'Windows'	, NULL			, '9cafd844-d29a-4cd4-840f-9d1a16c3118e', 'Stage - E - WindowsAuth - All Nodes' )
		, ( 'P'	, 'E'			, 'All'		, 'Windows'	, NULL			, 'ec1f5403-828c-4246-a201-e820c7714eee', 'Prod - E - WindowsAuth - All Nodes' )

		, ( 'D'	, 'E'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, '6a4ceafc-a6b2-4c39-897e-caf0ebaa22f3', 'Dev - E - DeployUser' )
		, ( 'T'	, 'E'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, '3335c348-3654-4324-bdd7-357200c1f38b', 'Test - E - DeployUser' )
		, ( 'S'	, 'E'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, '697d0769-1215-49f0-a918-d18ea8ea0fa1', 'Stage - E - DeployUser' )
		, ( 'P'	, 'E'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'c17e2edd-bdc4-4020-9600-b94d6310a0fb', 'Prod - E - DeployUser' )

		, ( 'D'	, 'E'			, 'CNAME'	, 'SQL'		, ''			, '52f49e85-9927-4080-a442-d643d05432ec', 'Dev - E - SQLAuth' )
		, ( 'T'	, 'E'			, 'CNAME'	, 'SQL'		, ''			, '9f90a022-c7ad-4a78-8d6b-a8e4dd422ac6', 'Test - E - SQLAuth' )
		, ( 'S'	, 'E'			, 'CNAME'	, 'SQL'		, ''			, '0704f198-e880-4f92-9001-27185c240f66', 'Stage - E - SQLAuth' )
		, ( 'P'	, 'E'			, 'CNAME'	, 'SQL'		, ''			, '5b2e7fb0-ced3-4951-8f8f-f2a40e794bb9', 'Prod - E - SQLAuth' )

		, ( 'T'	, 'E'			, 'All'		, 'SQL'		, 'DeployUser'	, '76e8a956-bc37-4a07-ba3a-94050371e84d', 'Test - E - DeployUser - All Nodes' )
		, ( 'S'	, 'E'			, 'All'		, 'SQL'		, 'DeployUser'	, 'dad6400c-b386-494e-8b0e-8ab2433df47b', 'Stage - E - DeployUser - All Nodes' )
		, ( 'P'	, 'E'			, 'All'		, 'SQL'		, 'DeployUser'	, 'd3045899-77e1-406a-815c-414c016247ea', 'Prod - E - DeployUser - All Nodes' )

		, ( 'T'	, 'E'			, 'All'		, 'SQL'		, ''			, 'c84548a0-b2cc-4ecd-b998-21c22e6026d7', 'Test - E - SQLAuth - All Nodes' )
		, ( 'S'	, 'E'			, 'All'		, 'SQL'		, ''			, 'cd11e777-85cd-4f4e-a41e-9e0f7c896f7c', 'Stage - E - SQLAuth - All Nodes' )
		, ( 'P'	, 'E'			, 'All'		, 'SQL'		, ''			, '78b4b015-1adc-48bd-a13f-e9c56ad1677e', 'Prod - E - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- GA
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'GA'	, 'CNAME'	, 'Windows'	, NULL			, '921784d8-c641-4d88-976d-f2ed88e10647', 'Dev - GA - WindowsAuth' )
		, ( 'T'	, 'GA'	, 'CNAME'	, 'Windows'	, NULL			, '3f09caeb-abab-4388-8e58-f6970627b881', 'Test - GA - WindowsAuth' )
		, ( 'S'	, 'GA'	, 'CNAME'	, 'Windows'	, NULL			, '882a4c0d-ec77-4edc-96d0-518027b5d21f', 'Stage - GA - WindowsAuth' )
		, ( 'P'	, 'GA'	, 'CNAME'	, 'Windows'	, NULL			, '1f936338-da86-4002-9317-2d0856292ce2', 'Prod - GA - WindowsAuth' )

		, ( 'T'	, 'GA'	, 'All'		, 'Windows'	, NULL			, '7dacfb14-e8c5-438c-8350-1c2efeead6cb', 'Test - GA - WindowsAuth - All Nodes' )
		, ( 'S'	, 'GA'	, 'All'		, 'Windows'	, NULL			, 'aa9d89b8-afa6-4c5a-be91-2b2e3e6bb535', 'Stage - GA - WindowsAuth - All Nodes' )
		, ( 'P'	, 'GA'	, 'All'		, 'Windows'	, NULL			, 'cbfee66e-8aa7-496b-a960-ed3aad255ecf', 'Prod - GA - WindowsAuth - All Nodes' )

		, ( 'D'	, 'GA'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'a3583223-edf5-4370-a22e-279db3ecca15', 'Dev - GA - DeployUser' )
		, ( 'T'	, 'GA'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '51048143-f240-4c7f-b816-2e3eb33261b7', 'Test - GA - DeployUser' )
		, ( 'S'	, 'GA'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '84ba00a4-ff77-4d28-9641-3f83f296fd0a', 'Stage - GA - DeployUser' )
		, ( 'P'	, 'GA'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'cfacdbcf-5dc3-424e-84b8-bbca69f952ac', 'Prod - GA - DeployUser' )

		, ( 'D'	, 'GA'	, 'CNAME'	, 'SQL'		, ''			, '6d9973ab-5a82-420e-a2c7-0d85fe412380', 'Dev - GA - SQLAuth' )
		, ( 'T'	, 'GA'	, 'CNAME'	, 'SQL'		, ''			, '23aaa66e-43b6-4fe2-971c-30546a41d663', 'Test - GA - SQLAuth' )
		, ( 'S'	, 'GA'	, 'CNAME'	, 'SQL'		, ''			, '4290dd09-8de7-44e9-bdbd-b47d532b2bcd', 'Stage - GA - SQLAuth' )
		, ( 'P'	, 'GA'	, 'CNAME'	, 'SQL'		, ''			, 'b6062b0a-4cb2-407d-b040-8fc88416077c', 'Prod - GA - SQLAuth' )

		, ( 'T'	, 'GA'	, 'All'		, 'SQL'		, 'DeployUser'	, '6deac2e5-a336-46d0-a958-255ddd126e5b', 'Test - GA - DeployUser - All Nodes' )
		, ( 'S'	, 'GA'	, 'All'		, 'SQL'		, 'DeployUser'	, '7c6cae00-3294-4b27-9f7c-f7475a6ed7ac', 'Stage - GA - DeployUser - All Nodes' )
		, ( 'P'	, 'GA'	, 'All'		, 'SQL'		, 'DeployUser'	, 'eb9baa58-8068-451c-8007-a7ad405b1d3c', 'Prod - GA - DeployUser - All Nodes' )

		, ( 'T'	, 'GA'	, 'All'		, 'SQL'		, ''			, 'f95d2872-583a-40ba-826b-3793098086af', 'Test - GA - SQLAuth - All Nodes' )
		, ( 'S'	, 'GA'	, 'All'		, 'SQL'		, ''			, '37abe588-d792-4827-89a1-9dd5f122a99b', 'Stage - GA - SQLAuth - All Nodes' )
		, ( 'P'	, 'GA'	, 'All'		, 'SQL'		, ''			, '69a359f3-5d0d-4321-b79b-32399ccb32ca', 'Prod - GA - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- I
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'I'	, 'CNAME'	, 'Windows'	, NULL			, 'a9413e03-65eb-4b4b-8d11-eaab0deb69d3', 'Dev - I - WindowsAuth' )
		, ( 'T'	, 'I'	, 'CNAME'	, 'Windows'	, NULL			, 'd3a13922-c111-43eb-bc01-0314bde69e43', 'Test - I - WindowsAuth' )
		, ( 'S'	, 'I'	, 'CNAME'	, 'Windows'	, NULL			, '488826e5-2f16-441e-9c84-c69044d9ba18', 'Stage - I - WindowsAuth' )
		, ( 'P'	, 'I'	, 'CNAME'	, 'Windows'	, NULL			, '1e54a884-e60a-4ecf-8efb-2f9af2c20943', 'Prod - I - WindowsAuth' )

		, ( 'T'	, 'I'	, 'All'		, 'Windows'	, NULL			, '5cbaf74b-87c6-4e7c-a1aa-db21ccf1d89e', 'Test - I - WindowsAuth - All Nodes' )
		, ( 'S'	, 'I'	, 'All'		, 'Windows'	, NULL			, 'c616868b-eed2-4f20-afad-dabda1d5bef1', 'Stage - I - WindowsAuth - All Nodes' )
		, ( 'P'	, 'I'	, 'All'		, 'Windows'	, NULL			, '8e10a6ed-1e60-4786-ac00-a9a84e6d5787', 'Prod - I - WindowsAuth - All Nodes' )

		, ( 'D'	, 'I'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '171be28a-a237-4dc6-8c59-43aa0f16fe36', 'Dev - I - DeployUser' )
		, ( 'T'	, 'I'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'f3af40b1-633f-4a55-a4a7-3ddf31e1023e', 'Test - I - DeployUser' )
		, ( 'S'	, 'I'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '1d23178a-3555-4198-97a0-4db64063943c', 'Stage - I - DeployUser' )
		, ( 'P'	, 'I'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '432af81d-2b2e-4e6d-bc39-f9c4817c2e5a', 'Prod - I - DeployUser' )

		, ( 'D'	, 'I'	, 'CNAME'	, 'SQL'		, ''			, '81bc7067-0c96-4675-9167-a3d8b8668694', 'Dev - I - SQLAuth' )
		, ( 'T'	, 'I'	, 'CNAME'	, 'SQL'		, ''			, 'd10d8af7-ab0e-417b-bfee-a07bc3e9b5c5', 'Test - I - SQLAuth' )
		, ( 'S'	, 'I'	, 'CNAME'	, 'SQL'		, ''			, 'ebc18483-7ae1-46f7-8d26-fa075888998a', 'Stage - I - SQLAuth' )
		, ( 'P'	, 'I'	, 'CNAME'	, 'SQL'		, ''			, 'f7d0af99-e296-41e8-b949-e7158484abf0', 'Prod - I - SQLAuth' )

		, ( 'T'	, 'I'	, 'All'		, 'SQL'		, 'DeployUser'	, '5b50c8e2-9e0c-45f7-88a0-b9680226a2af', 'Test - I - DeployUser - All Nodes' )
		, ( 'S'	, 'I'	, 'All'		, 'SQL'		, 'DeployUser'	, '5340fbfa-5440-44f5-9869-c09ff202f9ba', 'Stage - I - DeployUser - All Nodes' )
		, ( 'P'	, 'I'	, 'All'		, 'SQL'		, 'DeployUser'	, 'c9a48f67-4e23-4603-bd19-ca676746783f', 'Prod - I - DeployUser - All Nodes' )

		, ( 'T'	, 'I'	, 'All'		, 'SQL'		, ''			, 'e099d074-fd8d-4d93-bafe-218547dbe0b3', 'Test - I - SQLAuth - All Nodes' )
		, ( 'S'	, 'I'	, 'All'		, 'SQL'		, ''			, 'b2c005be-9bdb-4d16-9e07-10feb9e422a0', 'Stage - I - SQLAuth - All Nodes' )
		, ( 'P'	, 'I'	, 'All'		, 'SQL'		, ''			, 'ddb0ed70-b229-4406-b7c7-d5749e3f8b17', 'Prod - I - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- R
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'R'	, 'CNAME'	, 'Windows'	, NULL			, 'f091bfe3-6eb6-4623-bd51-6ef4268d2880', 'Dev - Report - WindowsAuth' )
		, ( 'T'	, 'R'	, 'CNAME'	, 'Windows'	, NULL			, '2273118d-18ae-4b6b-a5a4-f4fd821ced72', 'Test - R - WindowsAuth' )
		, ( 'S'	, 'R'	, 'CNAME'	, 'Windows'	, NULL			, 'e2206895-f6fb-4e4e-8501-b1987229959f', 'Stage - R - WindowsAuth' )
		, ( 'P'	, 'R'	, 'CNAME'	, 'Windows'	, NULL			, '063bffd2-71e0-40e8-bd2f-f51893fd2886', 'Prod - R - WindowsAuth' )

		, ( 'T'	, 'R'	, 'All'		, 'Windows'	, NULL			, '7548b998-13f4-4e74-bfd5-975d40c29e39', 'Test - R - WindowsAuth - All Nodes' )
		, ( 'S'	, 'R'	, 'All'		, 'Windows'	, NULL			, '98b489ac-868d-438f-8be4-20144c867051', 'Stage - R - WindowsAuth - All Nodes' )
		, ( 'P'	, 'R'	, 'All'		, 'Windows'	, NULL			, '19218594-10bb-45ba-b564-267be962e540', 'Prod - R - WindowsAuth - All Nodes' )

		, ( 'D'	, 'R'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '35f5b06b-deb7-46de-ba2c-fe558cf16b2f', 'Dev - R - DeployUser' )
		, ( 'T'	, 'R'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, '82d53640-670e-4347-810f-9139158a452c', 'Test - R - DeployUser' )
		, ( 'S'	, 'R'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'd5f4ab4e-f6f7-4b62-98d5-90af0e42aa60', 'Stage - R - DeployUser' )
		, ( 'P'	, 'R'	, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'b0de4900-f892-46f8-97b3-a333bd72c779', 'Prod - R - DeployUser' )

		, ( 'D'	, 'R'	, 'CNAME'	, 'SQL'		, ''			, 'ca724864-0221-411f-90d1-ecd202739fdc', 'Dev - R - SQLAuth' )
		, ( 'T'	, 'R'	, 'CNAME'	, 'SQL'		, ''			, '1fab2d3b-8229-43e8-b66e-aaa928359df9', 'Test - R - SQLAuth' )
		, ( 'S'	, 'R'	, 'CNAME'	, 'SQL'		, ''			, '895b49b9-f17f-4553-bb32-16590d89e36d', 'Stage - R - SQLAuth' )
		, ( 'P'	, 'R'	, 'CNAME'	, 'SQL'		, ''			, 'f54dcd64-f181-48ca-b266-87e170533b19', 'Prod - R - SQLAuth' )

		, ( 'T'	, 'R'	, 'All'		, 'SQL'		, 'DeployUser'	, '16f48db1-52eb-45f2-afff-975d2b756cff', 'Test - R - DeployUser - All Nodes' )
		, ( 'S'	, 'R'	, 'All'		, 'SQL'		, 'DeployUser'	, 'f5803291-47ad-44cd-9358-8a395e1689e5', 'Stage - R - DeployUser - All Nodes' )
		, ( 'P'	, 'R'	, 'All'		, 'SQL'		, 'DeployUser'	, 'c2fbc5c2-8009-4a98-9cad-bd503edcceac', 'Prod - R - DeployUser - All Nodes' )

		, ( 'T'	, 'R'	, 'All'		, 'SQL'		, ''			, 'f465964d-eb7f-4f6f-97ca-2c5bd2aec1e1', 'Test - R - SQLAuth - All Nodes' )
		, ( 'S'	, 'R'	, 'All'		, 'SQL'		, ''			, '45f20da2-96b4-444d-97d4-4f80bacad4d0', 'Stage - R - SQLAuth - All Nodes' )
		, ( 'P'	, 'R'	, 'All'		, 'SQL'		, ''			, '2381b4fe-fc30-41d7-bcdb-c8751ded9aa3', 'Prod - R - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- SSISDB
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType	,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'SSISDB'		, 'CNAME'	, 'Windows'	, NULL			, '4eb32f6b-4424-4a82-ba59-fffabca5b3cf', 'Dev - SSISDB - WindowsAuth' )
		, ( 'T'	, 'SSISDB'		, 'CNAME'	, 'Windows'	, NULL			, '22207793-9b08-4683-8da2-203768d46a2d', 'Test - SSISDB - WindowsAuth' )
		, ( 'S'	, 'SSISDB'		, 'CNAME'	, 'Windows'	, NULL			, 'bf9d1284-8bb5-4089-963f-cf85977ac41e', 'Stage - SSISDB - WindowsAuth' )
		, ( 'P'	, 'SSISDB'		, 'CNAME'	, 'Windows'	, NULL			, 'bb44c8db-f0df-4757-ac8e-fde2018679ca', 'Prod - SSISDB - WindowsAuth' )

		, ( 'T'	, 'SSISDB'		, 'All'		, 'Windows'	, NULL			, '4d29f138-d416-459c-be78-eb76ed04889d', 'Test - SSISDB - WindowsAuth - All Nodes' )
		, ( 'S'	, 'SSISDB'		, 'All'		, 'Windows'	, NULL			, 'ce0ed0f4-ab15-4bb4-a75e-156a9f218693', 'Stage - SSISDB - WindowsAuth - All Nodes' )
		, ( 'P'	, 'SSISDB'		, 'All'		, 'Windows'	, NULL			, 'a7889cb2-c7c0-418a-bb9b-e3796768ed2d', 'Prod - SSISDB - WindowsAuth - All Nodes' )

		, ( 'D'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'd472690d-69f6-494f-b1df-f39e761d1bcc', 'Dev - SSISDB - DeployUser' )
		, ( 'T'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '3ddac83e-77da-420f-9ec3-663d7baaed1f', 'Test - SSISDB - DeployUser' )
		, ( 'S'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, '676c403c-056f-4c58-a6a9-8a84d2c84ca7', 'Stage - SSISDB - DeployUser' )
		, ( 'P'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'b0309f2b-0c56-4104-9e63-b07bbccc5ba9', 'Prod - SSISDB - DeployUser' )

		, ( 'D'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, ''			, '01f9327a-5237-409a-b94e-89c90b5df0a4', 'Dev - SSISDB - SQLAuth' )
		, ( 'T'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, ''			, '301e8388-7ca3-4363-9c0d-81a36864fea4', 'Test - SSISDB - SQLAuth' )
		, ( 'S'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, ''			, '69e001d7-feee-4e29-b347-8d08ff6fce1a', 'Stage - SSISDB - SQLAuth' )
		, ( 'P'	, 'SSISDB'		, 'CNAME'	, 'SQL'		, ''			, 'e514bef2-d26c-4312-a1b0-304e887e9b82', 'Prod - SSISDB - SQLAuth' )

		, ( 'T'	, 'SSISDB'		, 'All'		, 'SQL'		, 'DeployUser'	, '7305136e-e470-4955-b980-8e529f04a3b5', 'Test - SSISDB - DeployUser - All Nodes' )
		, ( 'S'	, 'SSISDB'		, 'All'		, 'SQL'		, 'DeployUser'	, 'aa262244-615a-4a48-9522-9d3a073acfa7', 'Stage - SSISDB - DeployUser - All Nodes' )
		, ( 'P'	, 'SSISDB'		, 'All'		, 'SQL'		, 'DeployUser'	, '81dd6aa8-768c-4d32-af02-299a01e82659', 'Prod - SSISDB - DeployUser - All Nodes' )

		, ( 'T'	, 'SSISDB'		, 'All'		, 'SQL'		, ''			, '8731ca2f-fcaf-4604-9efd-1f13cff0625d', 'Test - SSISDB - SQLAuth - All Nodes' )
		, ( 'S'	, 'SSISDB'		, 'All'		, 'SQL'		, ''			, '4652c0df-93b7-4f8c-9481-a89735299cf5', 'Stage - SSISDB - SQLAuth - All Nodes' )
		, ( 'P'	, 'SSISDB'		, 'All'		, 'SQL'		, ''			, 'e6ce7521-00f2-46f9-9133-77a74c122e6c', 'Prod - SSISDB - SQLAuth - All Nodes' )

		----------------------------------------------------------------------------------------------------------------------------------------
		-- V
		----------------------------------------------------------------------------------------------------------------------------------------
		-- Env	, DBType	,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName

		, ( 'D'	, 'V'			, 'CNAME'	, 'Windows'	, NULL			, '6596546d-403b-4298-86b9-a4aa0b2133cf', 'Dev - V - WindowsAuth' )
		, ( 'T'	, 'V'			, 'CNAME'	, 'Windows'	, NULL			, '78d14fd5-9207-44d2-905b-41bcc507edb7', 'Test - V - WindowsAuth' )
		, ( 'S'	, 'V'			, 'CNAME'	, 'Windows'	, NULL			, 'bec2bd92-0583-4e80-a396-fbfe412880b2', 'Stage - V - WindowsAuth' )
		, ( 'P'	, 'V'			, 'CNAME'	, 'Windows'	, NULL			, '233d4685-8a53-445d-83c4-781316d4f0e5', 'Prod - V - WindowsAuth' )

		, ( 'T'	, 'V'			, 'All'		, 'Windows'	, NULL			, '0c9fff24-cdb7-405c-a08d-039b6611d9ca', 'Test - V - WindowsAuth - All Nodes' )
		, ( 'S'	, 'V'			, 'All'		, 'Windows'	, NULL			, '1874ed81-4521-4266-a6f2-9d8e8c59f88a', 'Stage - V - WindowsAuth - All Nodes' )
		, ( 'P'	, 'V'			, 'All'		, 'Windows'	, NULL			, 'e2d46f55-186a-4739-bdf8-5e5a19a4e1a7', 'Prod - V - WindowsAuth - All Nodes' )

		, ( 'D'	, 'V'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, '4a201823-0d71-4ce2-8053-a6ad02555413', 'Dev - V - DeployUser' )
		, ( 'T'	, 'V'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, 'e3b1c1b7-88b1-427f-a631-9f27f264d00c', 'Test - V - DeployUser' )
		, ( 'S'	, 'V'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, '7d719ce6-3310-435c-9206-c96f5bcb4a75', 'Stage - V - DeployUser' )
		, ( 'P'	, 'V'			, 'CNAME'	, 'SQL'		, 'DeployUser'	, '8d77bee9-bc58-40f6-8ac1-196a7aca2d72', 'Prod - V - DeployUser' )

		, ( 'D'	, 'V'			, 'CNAME'	, 'SQL'		, ''			, '7e7bc229-d613-45d3-b626-20b00b203095', 'Dev - V - SQLAuth' )
		, ( 'T'	, 'V'			, 'CNAME'	, 'SQL'		, ''			, '54548e94-1cd5-455f-9a55-afb5847d2a8a', 'Test - V - SQLAuth' )
		, ( 'S'	, 'V'			, 'CNAME'	, 'SQL'		, ''			, '54036b85-097b-4390-a659-8cc396b4aa78', 'Stage - V - SQLAuth' )
		, ( 'P'	, 'V'			, 'CNAME'	, 'SQL'		, ''			, '241db210-433c-479e-9edb-afee3cfa684d', 'Prod - V - SQLAuth' )

		, ( 'T'	, 'V'			, 'All'		, 'SQL'		, 'DeployUser'	, '59703c85-eff7-4c28-98a5-e1fb435e5cc5', 'Test - V - DeployUser - All Nodes' )
		, ( 'S'	, 'V'			, 'All'		, 'SQL'		, 'DeployUser'	, '29bf7620-974b-4b5f-ad5d-ec404b6a51e0', 'Stage - V - DeployUser - All Nodes' )
		, ( 'P'	, 'V'			, 'All'		, 'SQL'		, 'DeployUser'	, '519cfcb8-9d95-4f73-afd5-8de0139b65de', 'Prod - V - DeployUser - All Nodes' )

		, ( 'T'	, 'V'			, 'All'		, 'SQL'		, ''			, '360dd565-13fa-4948-8e76-c12b527dcebe', 'Test - V - SQLAuth - All Nodes' )
		, ( 'S'	, 'V'			, 'All'		, 'SQL'		, ''			, '7acc8216-2a21-4be0-a62c-feec017c2360', 'Stage - V - SQLAuth - All Nodes' )
		, ( 'P'	, 'V'			, 'All'		, 'SQL'		, ''			, '7c39c1bd-48a6-4b76-ac9f-a2b0cb92d378', 'Prod - V - SQLAuth - All Nodes' )

	) AS X (Env	, DBType	,  NodeType	, AuthType	, SQLUserName	, GroupGuid								, GroupName);
GO